ignition-common-3: Fix build
acxz/gazebo-arch pull request #27
Opened 2022-05-20 09:14 UTC by alexdewar

This PR addresses two issues:
- ignition-common-3: Update sha256sums and dir name
- Add missing #include

The package now builds happily again :-)

2022-05-24 15:52 UTC, acxz requested changes

2022-05-24 15:52 UTC, acxz commented on ignition-common-3/PKGBUILD
> +  patch -p1 < ../missing-include-cstring.patch
Can you make this an upstream patch like so:
https://github.com/acxz/gazebo-arch/blob/74501764bd86da0f58475ebb2750af5525fd2e26/ignition-common/PKGBUILD#L15

2022-05-24 19:54 UTC, acxz commented on ignition-common-3/PKGBUILD
>  provides=("ignition-common=$pkgver")
can we make this just `=3` so major version dep can be caught and not just the specific `3.14.0` version.

2022-05-25 13:20 UTC, alexdewar commented
> Looks like i forgot to mention that the `url` should be changed as well to gazebosim.org instead of ignitionrobotics.
Good point. I'll do that.
> 
> Any reason for introducing the `_url`? I'd pref source links to be hardcoded since they won't be changing/consistancy with the rest of the packages.
The source links *are* hardcoded. ``$_url`` doesn't change anywhere.

2022-06-03 16:29 UTC, merged