[gazebo] replace 'putstr' attribute with 'printf'
acxz/gazebo-arch pull request #33
Opened 2022-06-11 21:27 UTC by Maik93

This should fixes #32.

2022-06-11 23:00 UTC, acxz commented
We don't accept direct modifications to the source code via the PKGBUILD if we can help it.

Can you make a PR to the official gazebo repo with your change and then we'll add it in as patch file?

2022-06-12 09:54 UTC, Sir-Photch commented
Compiles for me

2022-06-12 17:29 UTC, Maik93 commented
Hi @acxz, I managed to make a PR on Gazebo11 too: https://github.com/osrf/gazebo/pull/3228.
What is the next step?

2022-06-12 17:39 UTC, acxz commented
The next step is the change this PR so that it pulls in the patch file from the PR directly take a look at how its done in `ignition-common` like so:

https://github.com/acxz/gazebo-arch/blob/74501764bd86da0f58475ebb2750af5525fd2e26/ignition-common/PKGBUILD#L15-L24

2022-06-12 23:54 UTC, acxz requested changes
Please also update the pkgrel and the `.SRCINFO` file.

2022-06-13 13:42 UTC, acxz commented
@Maik93 thanks for making upstream PR. Seems like its a fix that upstream doesn't want so we'll go ahead with your original `sed` based patch until graphviz-4.0.1 is released. Go ahead and update the pkgrel and .SRCINFO and I'll merge this pupper in.

2022-07-08 14:13 UTC, closed without merging