gazebo classic use legacy packages
acxz/gazebo-arch pull request #52
Opened 2023-03-04 07:38 UTC by muellerbernd

I modified the PKGBUILD of gazebo classic so that it uses the legacy packages

2023-03-06 03:32 UTC, acxz requested changes

2023-03-06 03:32 UTC, acxz commented on gazebo/PKGBUILD
> +         'ignition-cmake-2' 'ignition-common-3' 'ignition-fuel_tools-4' 'ignition-msgs-5' 'tinyxml2' 'qwt')
Can you replace with an `=`'s?

Also thanks for bumping the pkgrel, but make sure to update the .SRCINFO as well with the `makepkg --printsrcinfo > .SRCINFO` command.

2023-03-06 22:34 UTC, acxz commented on gazebo/PKGBUILD
> +         'ignition-cmake-2' 'ignition-common-3' 'ignition-fuel_tools-4' 'ignition-msgs-5' 'tinyxml2' 'qwt')
Thx

2023-03-06 22:37 UTC, acxz approved these changes

2023-03-06 22:37 UTC, acxz commented
@alexdewar requesting final merge and push to AUR

2023-03-10 08:12 UTC, muellerbernd commented
I had problems with ignition-common-3 since the last update of ffmpeg to version so I made a patch. Now ignition-common-3 builds fine. The patch was inspired from [here](https://github.com/obsproject/obs-studio/pull/8376).

2023-03-11 18:19 UTC, acxz requested changes
Can you please separate the changes to `ignition-common-3` as a separate PR? separate PKGBUILD, separate PR.

2023-03-11 18:59 UTC, closed without merging

2023-03-11 19:22 UTC, muellerbernd commented
closed this issue and created a new one for gazebo-classic  in #54. For ignition-common-3 I created a new PR in #55